server:
  port: 8092

spring:
  application:
    name: SearchService
  elasticsearch:
    uris: http://elasticsearch:9200

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-search-group
      auto-offset-reset: earliest